### ISSUE TITLE
Carry the org/space/app name in the structured data part of the syslog message

### ISSUE THREAD

**Issue by istvanballok** [cloudfoundry/loggregator-release#272]
An [issue][1] was raised some time ago for the loggregator component to include
human readable names for organizations, spaces and apps in the log messages to
facilitate the creation of meaningful dashboards in Kibana. (Note that some of
the comments of that issue give valuable and detailed insights into the
implications of this approach.)

This capability was implemented recently in [Loggregator v77][2]: "'loggregator'
has been replaced by app, org and space name for host name in syslog drains".
([pivotal tracker issue][3], [Loggregator merge commit][4])

However, there are some [restrictions][5] on the length of the hostname field
and the allowed characters, so the org, space and app names are [adjusted][6]
after they are concatenated in the Cloud Controller. This means that the
original org, space and app names cannot (always) be recovered from the hostname
field of the syslog message.

The structured data field of the syslog protocol [RFC-5424][7] is not impacted
by such restrictions so maybe we could use that instead of the hostname field to
carry the org, space and app names (and ids) in the log message.

[1]: https://github.com/cloudfoundry/loggregator/issues/48
[2]: https://github.com/cloudfoundry/loggregator/releases/tag/v77
[3]: https://www.pivotaltracker.com/n/projects/993188/stories/135545713
[4]: https://github.com/cloudfoundry/loggregator/commit/bae09b3cb8d47c4203091048e97b0bb94071b951
[5]: https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames
[6]: https://github.com/cloudfoundry/cloud_controller_ng/blob/ca615b39eab405bf55e5e4b87ca44fc8b5a476a4/app/controllers/internal/syslog_drain_urls_controller.rb#L49-L53
[7]: https://tools.ietf.org/html/rfc5424

**Comment by jtuchscherer** [comment]
@istvanballok 
Sorry for taking such a long time to respond to this.

We - the loggregator team - agree that your solution would work well and is preferable over the current implementation. But changing our syslog message format comes with a big impact. We would break everybody who relies on the message being what it is right now.

I am going to go ahead and close this issue for now. Please feel free to re-open if this continues to be a big pain point for you.

Thanks
