### ISSUE TITLE
Metron does not limit the size of the ingress envelopes in v2

### ISSUE THREAD

**Issue by poy** [cloudfoundry/loggregator-release#276]
In v1, Loggregator had a 64KiB limit enforced via UDP. Several assumptions (e.g., diode sizes) are based on a maximum envelope size of 64Kib. Therefore, we need a gate in v2 as well.

**Comment by bradylove** [comment]
I looked into this some more, from what I can tell our options are:

* The ingress receivers in the agent and router check the envelope sizes and reject if too large.
* We set `grpc.MaxMsgSize` to the max size of a batch.

**Comment by apoydence** [comment]
I think those would mitigate the risk.

**Comment by pianohacker** [comment]
Closing, stale.
