### ISSUE TITLE
Cert generation for metron does not include localhost/127.0.0.1 as SANs

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/loggregator-release#281]
The certs we generate for metron's gRPC mutual auth TLS server only contain the CN (Common Name) `metron`. This makes it difficult to connect to metron. Most of the time clients will be connecting to `localhost:3458` or `127.0.0.1:3458` and not `metron:3458` as the latter does not resolve. I ran into this during the hackday when I wrote a python program to send data into metron. Python does not make it easy to override the validation of CN/SANs (Subject Alternative Names) from the client. As a result I had to add an entry to `/etc/hosts` as a hack just to get it to work. Additionally, the error message python's gRPC bindings gave was not helpful. It took me a while to realize what was going on.

This came up once before when @jvshahid was doing the integration work with metron for diego. I searched through tracker and github issues but can not find the previous story. I assume it was deleted. He was able to solve the issue on his end as Go makes it very easy to override the validation of CN/SANs by setting `tls.Config.ServerName`. This is very user hostile however.

I recommend adding the following SANs to metron's cert:

- `localhost`
- `127.0.0.1`
- `ip6-localhost`
- `::1`

This may have some undesirable effects as metron uses the same cert for both listening on `localhost` as a gRPC server and as a client to doppler. We might want to think through the possible problems with using a client cert with these SANs. If it is a problem we can always use two different certs.

For reference, this is how we currently generate certs for metron:

- [cf-release](https://github.com/cloudfoundry/loggregator/blob/671036ddda364d48ef225b96bf7dc2911794b4f9/scripts/generate-loggregator-certs#L51-L53)
- [cf-deployment](https://github.com/cloudfoundry/cf-deployment/blob/7474ad0d98e2b8587765b14508ff8f3cece89628/cf-deployment.yml#L1541-L1548)

**Comment by JohannaSmith** [comment]
@jasonkeene Would you like to submit a PR for this issue?

**Comment by jasonkeene** [comment]
@

**Comment by jasonkeene** [comment]
@enocom Expressed the possibility of security concerns with adding `localhost` to the SANs. I don't think there are any security concerns. The agent only ever listens on localhost. Thus any client connecting to the agent and receiving the certificate **MUST** do so by connecting to `localhost`, `127.0.0.1`, `ip6-localhost`, or `::1`. There is no DNS or `/etc/host` entry for `metron` so connecting to `metron` is not possible. This means you have to override the default validation behaviour on the client to get this to work. This is easy to do in Golang which is why it works but difficult to do in other languages.

**Comment by ajackson** [comment]
Given that metro only listens on localhost, I don't think it will be a security problem to add these to the cert.

**Comment by apoydence** [comment]
Given #352 has been merged, I'm closing this.
