### ISSUE TITLE
Instance Group Names are not case consistent

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/loggregator-release#305]
In standalone loggregator, the Instance Group Names have both hyphens and underscores:

```
bosh -e lite -d loggregator vms
Using environment '192.168.70.6' as client 'admin'

Task 389. Done

Deployment 'loggregator'

Instance                                                Process State  AZ  IPs           VM CID                                VM Type
consul/b6380559-705e-4b07-a109-8264b3480ff4             running        z1  10.244.0.143  0234ea96-33a4-4057-42ad-dca76d50ddd8  default
doppler/dc950c20-33a8-4d57-8222-e5e7481e68de            running        z1  10.244.0.144  1a5d4ba9-efd5-4169-72c4-84a58e767687  default
log-api/b7b94133-c8ff-491b-93c9-40ca39148b3e            running        z1  10.244.0.145  5297e314-609a-4b10-69d8-6e8bd9faf870  default
reverse_log_proxy/a8abad22-813e-48dd-b574-d21c078a6737  running        z1  10.244.0.146  3d21433c-f205-4243-7389-6bfe907cd797  default

4 vms

Succeeded
```

Seems like we should conform to underscores (see [cf-deployment](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml)).

**Comment by cppforlife** [comment]
ive been pushing people to use dashes (especially that dns names can only
contain dashes).

**Comment by apoydence** [comment]
@cppforlife what would the upgrade path look like from a bosh perspective of changing all of our job names?

**Comment by bradylove** [comment]
@apoydence looks like bosh supports migration. https://bosh.io/docs/migrated-from.html. I am unsure how this would work in cf-release, or if we are even worried about this in cf-release.

Example in cf-deployment: https://github.com/cloudfoundry/cf-deployment/commit/5028d27826308747680c919450d2613f800cebbc#diff-f39617caec1965e56248ce1bf556db4dR997

**Comment by JohannaSmith** [comment]
@apoydence let's address this again once purely on cf-deployment, should be easier to do the transition of instance group names at that time.
