### ISSUE TITLE
Feature Proposal: Custom Application Metrics

### ISSUE THREAD

**Issue by hev** [cloudfoundry/loggregator-release#309]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [ ] I found a bug - here are some steps to recreate it.
- [x] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

We review issues and PR's on a weekly basis and try to schedule and prioritize
items. If you are wondering about status of an item feel free to contact us on
our [slack channel](https://cloudfoundry.slack.com/messages/C02HCCXV5).

### Problem Summary ###
Currently, there is no standardized approach for applications to emit metrics. Loggregator is already delivering metrics through the Firehose for components and some services. This gap in functionality forces operators and developers to roll their own metric distribution mechanisms, rather the utilize the tooling already deployed. 

See the full [feature proposal](https://docs.google.com/document/d/1hjMO3plNBDwtqCgVIYsayhCcl0k-H0Hzvaaam4SSkto/edit#)

**Comment by pianohacker** [comment]
Closing, stale.
