### ISSUE TITLE
Feature Proposal: Improved Persistance Architecture

### ISSUE THREAD

**Issue by hev** [cloudfoundry/loggregator-release#311]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [ ] I found a bug - here are some steps to recreate it.
- [ ] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [x] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

We review issues and PR's on a weekly basis and try to schedule and prioritize
items. If you are wondering about status of an item feel free to contact us on
our [slack channel](https://cloudfoundry.slack.com/messages/C02HCCXV5).

### Problem Summary ###
Deployments with large number of dopplers experience latent responses when executing the command cf logs --recent. This is because the implementation of recent logs collects all logs for a particular app across each of the dopplers, and reassembles them to construct the response. This same architecture applies to container metrics so this latency affects the cf push in addition to cf logs recent.

See draft of [feature proposal](https://docs.google.com/document/d/1yhfl0EB_MkHkh4JdRZXGeQMx_BDMCuB-SpPuSrD3VOU/edit#)

**Comment by pianohacker** [comment]
Closing, stale.
