### ISSUE TITLE
Feature Proposal: Supported Event Type in Loggregator API

### ISSUE THREAD

**Issue by ahevenor** [cloudfoundry/loggregator-release#312]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [ ] I found a bug - here are some steps to recreate it.
- [x] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

We review issues and PR's on a weekly basis and try to schedule and prioritize
items. If you are wondering about status of an item feel free to contact us on
our [slack channel](https://cloudfoundry.slack.com/messages/C02HCCXV5).

### Problem Summary ###
Many monitoring platforms can handle the concept of events, but the Loggregator API doesn't support this. This forces operators and developers to use logs as events and limits the integration possibilities with third party tools. 

### Solution Summary ###
Provide a envelope type for events that nozzle developers can use to publish specific event types for the corresponding platform.

**Comment by bradylove** [comment]
@ahevenor since this has shipped can we close this issue?

**Comment by ahevenor** [comment]
@bradylove almost there. I wanted to accept a few final CLI stories and the close it out.

**Comment by ahevenor** [comment]
ACtually this one is complete. Closing and updating roadmap.
