### ISSUE TITLE
Feature Proposal: Syslog Drains for all Apps in a Space

### ISSUE THREAD

**Issue by ahevenor** [cloudfoundry/loggregator-release#313]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [ ] I found a bug - here are some steps to recreate it.
- [x] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

We review issues and PR's on a weekly basis and try to schedule and prioritize
items. If you are wondering about status of an item feel free to contact us on
our [slack channel](https://cloudfoundry.slack.com/messages/C02HCCXV5).

### Problem Summary ###
There is currently evidence that operators experience the following problems with the current solutions for directing app logs to a longer term storage solution.
* No OSS supported solution exists for getting all syslog output.
* Consuming the firehose via the firehose->syslog nozzle results in extra logs
* App Developers need to configure a drain for every app in order to save their logs persistently. 

See [feature proposal](https://docs.google.com/document/d/1Wi8WnS4avVhNLxn2TV9CwCsWH4kjlAPoXWDVzWDIQwE/edit#)

**Comment by bradylove** [comment]
@ahevenor @jtuchscherer,

Can we close this issue? I believe this is resolved by the `space-drain` in the `cf-drain-cli`.

**Comment by jtuchscherer** [comment]
@bradylove is correct. This is implemented in https://github.com/cloudfoundry/cf-drain-cli
