### ISSUE TITLE
Non 200 response from CC API: 400

### ISSUE THREAD

**Issue by wayneeseguin** [cloudfoundry/loggregator-release#316]
I was debugging with @jasonkeene and at one point we were blocked, the error message was simply:
`2017/09/06 18:04:34 Non 200 response from CC API: 400 for: e5ceb0d0-894d-4083-b795-90becd76ba2e` with no further details, and nothing was appearing in the CC logs.

Jason compiled a custom binary to try which output the body of that error message to which we saw:
```
2017/09/06 18:04:34 Non 200 response from CC API: 400 for: e5ceb0d0-894d-4083-b795-90becd76ba2e body: <html>
<head><title>400 No required SSL certificate was sent</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>No required SSL certificate was sent</center>
<hr><center>nginx</center>
</body>
</html>
```
It would be terrific if there was a flag that we could toggle to show the body of error messages and/or simply have more visibility when connections to other services error out.

Thanks!

**Comment by jasonkeene** [comment]
Some ideas we had to have a better experience for this:

- On startup, validate cert/key provided are signed by the CA cert provided.
- On startup, attempt to make a connection to CC to make sure 400s are not returning.
- Log the body or add a more descriptive error message when 400s occurs hinting that CC mTLS cert might be bad.

**Comment by apoydence** [comment]
After conversation with @jasonkeene, it looks like the problem was from incorrect TLS configuration. Closing.
