### ISSUE TITLE
Feature Proposal: Improving Mean Time to Determine "Noisy Neighbor" Impacting the Firehose

### ISSUE THREAD

**Issue by ahevenor** [cloudfoundry/loggregator-release#319]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [ ] I found a bug - here are some steps to recreate it.
- [x] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

We review issues and PR's on a weekly basis and try to schedule and prioritize
items. If you are wondering about status of an item feel free to contact us on
our [slack channel](https://cloudfoundry.slack.com/messages/C02HCCXV5).

## Problem Summary
Currently if a single application produces logs fast enough, and consistently enough it can exhaust resource throughout the Loggregator system and cause other application logs, or component metrics to be dropped. There is not specific monitoring tools for identifying this occurrence, and isolating the application can be challenging and impactful to operators. 

## Solution Summary
Mitigating noisy neighbor application should have the following operator experience. 
* An ability to rank producers of log volume by application instance GUID
* Defined log quotas at the application instance level
* Emit metrics when quota violations occur 

See [feature proposal](https://docs.google.com/document/d/19CI185yhEAD4wcdHoYTLJQZFkBhWZ4c17yBMxJ4yT-U/edit#heading=h.9zv4h9b2wspj)

**Comment by apoydence** [comment]
Does this feature proposal only include ingress? We have evidence to believe that TrafficController (and therefore possibly RLP) suffer from slow consumers. Meaning, a slow firehose nozzle could impact other consumer's.

**Comment by pivotal-todd-robbins** [comment]
This is becoming a common pain point in support. Frequently we are encountering systems where app developers neglect log output and overwhelm loggregator system. Often message throughput exceeds 50k+/second which would require scaling loggregator VM's to massive levels.

We do not currently have good methods to identify or reduce loggregator messages from specific noisy apps, so we are at mercy of developers to fix application. Any enhancements that would allow to either identify app that is source of log level or allow an administrator to reduce log rate of an application would be helpful.

Additionally, we have faced issues where nozzles like firehose-to-syslog have overwhelmed CC on noisy systems and resulted in system outages.

Please increase the priority of this feature request as it has real impact and become a regular occurrence.

**Comment by shinji62** [comment]
@pivotal-todd-robbins Only way that f2s can overwhelmed the CC is when we warm up  / refresh the 
 data cache (apps name and so on).  High traffic on loggregator stack should not have this behaviour

 For f2s you can easily remove `cf set-env your-app-name F2S_DISABLE_LOGGING true` the noisy logs apps from be sent to your syslog enpoint.

**Comment by ahevenor** [comment]
This is now available as the [noisy neighbor nozzle app](https://github.com/cloudfoundry/noisy-neighbor-nozzle) and [bosh release](https://github.com/cloudfoundry/noisy-neighbor-nozzle-release).
