### ISSUE TITLE
Feature Proposal: Syslog Blacbox Monitoring Tools

### ISSUE THREAD

**Issue by hev** [cloudfoundry/loggregator-release#324]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [ ] I found a bug - here are some steps to recreate it.
- [x] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

We review issues and PR's on a weekly basis and try to schedule and prioritize
items. If you are wondering about status of an item feel free to contact us on
our [slack channel](https://cloudfoundry.slack.com/messages/C02HCCXV5).

## Problem Summary
It is hard for developers and operators to identify if loss of logs in a syslog drain is due to Loggregator performance or the performance of their drain. Even sending a known amount of logs to a specified drain does not effectively rule out the potential of logs as it leaves the platform. 

## Solution Summary
Provide an application or set of applications similar to cf-logmon that which uses a blackbox approach to measure loss to a user provided drain. To do this the application will need to receive syslog data. Ideally this would be available in all supported protocols.

See [feature proposal](https://docs.google.com/document/d/1Sxy810BYmOJbBKhBN24u2Ey6RT5M_LF9KS-TI4q3Sy8/edit#heading=h.gzqvpeeoe0ow).

**Comment by Ruhul768** [comment]
8c229f30440d5ccdb75e0a32441ef2f2ec902687886c5bd863377784d6912968

**Comment by pianohacker** [comment]
Closing, stale.
