### ISSUE TITLE
Feature Proposal: Syslog Injector

### ISSUE THREAD

**Issue by hev** [cloudfoundry/loggregator-release#329]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [ ] I found a bug - here are some steps to recreate it.
- [x] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

We review issues and PR's on a weekly basis and try to schedule and prioritize
items. If you are wondering about status of an item feel free to contact us on
our [slack channel](https://cloudfoundry.slack.com/messages/C02HCCXV5).

## Problem Summary
Services producing logs in a standard syslog format, do not have a convenient way for ingressing those logs into Loggregator. This makes ideas like the Developer Segmented Firehose or Nozzles as a Service limited in potential. Also, some Operators would prefer all logs (Platform and Application) be combined into a single stream.

## Solution Summary
A simple component that can be bosh deployed that ingests syslog format, convert it to Loggregator API envelopes and send them to Metron with relevant tags included on the envelope. This would be similar to how the statsd-injector currently works. 

See [Feature Proposal](https://docs.google.com/document/d/1LGt2cEFZ_4SmOYrV9Ar83NWKnNBUeov989_A5uoaEdI/edit#heading=h.ltrfiiz2q3o6)

**Comment by pianohacker** [comment]
Closing, stale.
