### ISSUE TITLE
Feature Proposal  Export All Metron Properties in a Bosh Link

### ISSUE THREAD

**Issue by robertjsullivan** [cloudfoundry/loggregator-release#334]
As a user, I would like to be able to configure metron agent in my release using bosh links. It would be nice if I could consume a set of links to configure metron to doppler and my release to metron.

**Comment by apoydence** [comment]
Configuring a metron agent consists of few different properties:
1. Ports
2. Doppler discovery
3. TLS certs
4. Meta information (deployment, extra tags, etcd...)

What we can do with Bosh Links:
- Ports are simple and easily could be configured with bosh links.
- The bosh DNS feature track has taken care of Doppler discovery.

What we won't do with Bosh Links:
- It would be incorrect to configure certs with bosh links as that is credhub's responsibility.
- Meta information is normally specific to the instance group. Most data comes from the bosh spec anyways.

For connecting to metron, what information is your release trying to consume? I'm assuming ports and possibly certs? I believe both of those topics would be covered above.

**Comment by cppforlife** [comment]
> It would be incorrect to configure certs with bosh links as that is credhub's responsibility.

links are intended to be used with sensitive information. (links internally collaborate with credhub). you can think of them as service bindings (cf apps retrieve necessary info from a service binding to connect to service instance). 

if we are talking about including for metron agents to connect to doppler i would place that into link exposed by doppler.

happy to chat more.

**Comment by robertjsullivan** [comment]
Implementation concerns aside, I think connecting to metron should be akin to connecting to a database.  The bosh link for a db connection would provide the location and the authentication parameters so that you could just use it.   

Having to generate your own certs to authenticate with metron is a clunky user experience.

**Comment by apoydence** [comment]
@cppforlife Are other teams using links to connect to other subsystems?

This seems wrong to me. In fact I have an issue open on cf-deployment with how diego is connecting to metron: cloudfoundry/cf-deployment#310 that is similar.

@robertjsullivan Why would you not use a variable that has the `loggregator_ca` as the CA?

**Comment by cppforlife** [comment]
> Are other teams using links to connect to other subsystems?

they should if they arent. links are still being introduced through
cf-deployment so we are slowly getting there.

> This seems wrong to me. In fact I have an issue open on cf-deployment
with how diego is connecting to metron: cloudfoundry/cf-deployment#310
<https://github.com/cloudfoundry/cf-deployment/issues/310> that is similar.

i agree that we should try to kill off any cred reuse between multiple
clients. we have future enhancements to actually provide a *unique* link
contents to different consumers as they consume the link (same as typical
service binding).

> Why would you not use a variable that has the loggregator_ca as the CA?

that's a bit leaky imho. consumers shouldnt really care about backing CA or
whatever other inputs are necessary to provide ultimate contents of the
link (similar to service bindings).

**Comment by ahevenor** [comment]
I am closing this issue for now. With changes to how metron is included (Add on) I am not sure if this is still a need at this time.
