### ISSUE TITLE
Disabling metron's syslog config doesn't remove the conf file

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/loggregator-release#336]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [x] I found a bug - here are some steps to recreate it.
- [ ] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

We review issues and PR's on a weekly basis and try to schedule and prioritize
items. If you are wondering about status of an item feel free to contact us on
our [slack channel](https://cloudfoundry.slack.com/messages/C02HCCXV5).

When we disable the [`syslog_daemon_config.enable` flag](https://github.com/cloudfoundry/loggregator-release/blob/d4ee801fab0fd09d49041969818a560e5b7257d0/jobs/metron_agent/spec#L24) it doesn't remove `/etc/rsyslog.d/00-syslog_forwarder.conf` file and restarting the `rsyslog` service.

This is similar to [this issue on syslog-release](https://github.com/cloudfoundry/syslog-release/issues/27).

**Comment by apoydence** [comment]
@wfernandes 

Loggregator has cut ties with rsyslog and therefore do not want to add any additional "opinions" about how rsyslog is configured. I think [rsyslog-release](https://github.com/cloudfoundry/syslog-release) should be more opinionated about how it is configured and could take responsibility for cleaning up old configs. This would prevent Loggregator from stepping on any toes as rsyslog moves forward.
