### ISSUE TITLE
Feature Proposal: Deterministic Routing for Egress

### ISSUE THREAD

**Issue by ahevenor** [cloudfoundry/loggregator-release#348]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [ ] I found a bug - here are some steps to recreate it.
- [x] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

We review issues and PR's on a weekly basis and try to schedule and prioritize
items. If you are wondering about status of an item feel free to contact us on
our [slack channel](https://cloudfoundry.slack.com/messages/C02HCCXV5).

## Problem Summary

Random sharding of the firehose means that multiple instances can not probably perform calculations on counters. 

## Solution Summary
See [feature proposal](https://docs.google.com/document/d/1ULaylywgeocyBqmlLZ0_Td9S1eeqranHBZl2tsKEAQU/edit) from @knyar cc @johnsonj

**Comment by ahevenor** [comment]
This has shipped. Closing issue.

**Comment by youngm** [comment]
Any details of the resulting behaviour @ahevenor ?  I just finished creating my client side distributed firehose metric aggregator.  Can I throw that in the trash now?

**Comment by ahevenor** [comment]
@youngm - hopefully. You can use our RLPreader, and the deterministic name to test it out. See [here](https://github.com/cloudfoundry-incubator/loggregator-tools/blob/master/rlpreader/main.go#L25)
