### ISSUE TITLE
Feature Proposal: Service Drains

### ISSUE THREAD

**Issue by hev** [cloudfoundry/loggregator-release#349]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [ ] I found a bug - here are some steps to recreate it.
- [x] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

We review issues and PR's on a weekly basis and try to schedule and prioritize
items. If you are wondering about status of an item feel free to contact us on
our [slack channel](https://cloudfoundry.slack.com/messages/C02HCCXV5).

## Problem Summary
Because metrics are only available in the firehose, space developers do not have the necessary access to develop tooling and monitoring based on service metrics.  (This has been summarized previously in the Developer Segmented Firehose and Nozzle as a Service Feature Narratives)

## Solution Summary
This solution focuses on extending the capability of user provided syslog drains by the creation of a cf cli plugin and new drain-type functionality in the cf-syslog-drain release.

See [Feature Proposal](https://docs.google.com/document/d/1TWNucsNDbQD9Oxmc4ibOsKPdgmcw-AAPM-qAfnABdNU/edit#heading=h.efarh1epc9bb)

**Comment by pianohacker** [comment]
Closing, stale.
