### ISSUE TITLE
No instructions for deploying standalone to bosh-lite as requested by CONTRIBUTING.md

### ISSUE THREAD

**Issue by camelpunch** [cloudfoundry/loggregator-release#357]
Tell us why you are submitting?

- [X] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.

I'm trying to obey the `CONTRIBUTING.md` advice of 

> Run LATs in a standalone loggregator deployment on bosh-lite

However, there are no instructions for doing so. I've tried to use [loggregator.yml](https://github.com/cloudfoundry/loggregator-release/blob/develop/manifests/loggregator.yml) with [bosh-lite-ops.yml](https://github.com/cloudfoundry/loggregator-release/blob/develop/manifests/operations/bosh-lite-ops.yml), but it fails with:

```
Evaluating manifest:
  Expected to find exactly one matching array item for path '/instance_groups/name=consul' but found 0
```

Is the advice in `CONTRIBUTING.md` out of date? Is the ops file cruft? Am I doing something wrong? Is this much ado about nothing?

**Comment by ahevenor** [comment]
The contributing is lacking a link to them instructions for [stand alone loggregator](https://github.com/cloudfoundry/loggregator-release#standalone-loggregator)

**Comment by ahevenor** [comment]
Updated contributing.md with the link.

**Comment by camelpunch** [comment]
Thanks @ahevenor!
