### ISSUE TITLE
RLP not sending its logs to syslog

### ISSUE THREAD

**Issue by forbushbl** [cloudfoundry/loggregator-release#363]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [x] I found a bug - here are some steps to recreate it.
- [ ] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

We review issues and PR's on a weekly basis and try to schedule and prioritize
items. If you are wondering about status of an item feel free to contact us on
our [slack channel](https://cloudfoundry.slack.com/messages/C02HCCXV5).

## Summary
It appears that reverse_log_proxy does not send its own log (rlp.log) to syslog via `logger`. I know that eventually this will go away as everything gets moved to blackbox but in the interim, it would be great if these logs got forwarded so that we can have a centralized way of seeing these logs.

* [See how doppler does it](https://github.com/cloudfoundry/loggregator-release/blob/v101.6/jobs/doppler/templates/doppler_ctl.erb#L38)
* [See how this is missing from reverse_log_proxy](https://github.com/cloudfoundry/loggregator-release/blob/v101.6/jobs/reverse_log_proxy/templates/reverse_log_proxy_ctl.erb#L31-L32)

**Comment by ahevenor** [comment]
@forbushbl this is not handled within our release so I am going to close this issue. As you mentioned this should be resolved with updates to the [syslog-release](https://github.com/cloudfoundry/syslog-release).
