### ISSUE TITLE
doppler/trafficcontroller pprof port section of FAQ references the old default port

### ISSUE THREAD

**Issue by scottschulthess** [cloudfoundry/loggregator-release#369]
https://github.com/cloudfoundry/loggregator-release/wiki/FAQ references that 

> Component Pprof Port defaults to 6060 for Traffic Controller and Doppler or 6061 for Metron.

This should be updated to reflect that it now defaults to 0 which results in a random port at boot time that is declared in the logs according to  #368.

**Comment by scottschulthess** [comment]
Also https://github.com/cloudfoundry/loggregator-release/wiki/Loggregator-Component-Properties references the old ports

**Comment by wfernandes** [comment]
@scottschulthess I updated the wikis. Thanks for the find. 

@bradylove I believe that Loggregator has changed considerably since the writing of these wikis. I suggest either removing these wikis or putting up a *NOTE/WARNING* of some kind to indicate the staleness of the wiki pages.

**Comment by scottschulthess** [comment]
thanks @wfernandes! 

re: the state of the wiki page, in the case of the port I don't know if it also makes sense to add a note like that to the bosh specfile as that's what I tend to go-to for docs like that but perhaps theres a character limit

**Comment by wfernandes** [comment]
@scottschulthess Yeah...that does make sense. I'm sure the Loggregator team would have no problem doing that. :)
