### ISSUE TITLE
Proposal: Use node exporter to correlate vm metrics with bosh jobs

### ISSUE THREAD

**Issue by hev** [cloudfoundry/loggregator-release#370]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [ ] I found a bug - here are some steps to recreate it.
- [x] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

**Problem Summary**

In order to correlate VM metrics with bosh jobs operators must bring additional tooling and monitoring to observe a robust set of metrics.

 

**Solution Summary**

The following data pipeline is recommended.

Prometheus Node Exporter - This will be deployed as a bosh add on for presence on all VMS within the deployment
Prometheus Injector - This new component will be developed to consume any prometheus endpoint and send it to Loggregator Agent. It will report vm metrics for all bosh jobs (but not Loggregator Agent or itself). 
Node Exporter Whitelist - Depending on the potential impact and clutter that new additional metrics will provide, a set of filters may be recommended for the node-exporter

**Comment by pianohacker** [comment]
Closing, stale.
