### ISSUE TITLE
Metrics are emitted via UDP and gRPC in router

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/loggregator-release#372]
https://github.com/cloudfoundry/loggregator-release/blob/4df29cac42505ca64e06de2e66ee04c280fcdadc/jobs/doppler/spec#L68-L73

This is probably technical debt that needs to be taken care of. No reason to support both. Just confuses users.

**Comment by bradylove** [comment]
The router itself does not actually use the dropsonde port anymore and that property has been removed from the bosh job spec.
