### ISSUE TITLE
Trafficcontroller Spec Typo ? 

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [cloudfoundry/loggregator-release#374]
Hi, 

I've got a question. 
This line looks like a typo to me, is that the case or am I wrong?

https://github.com/cloudfoundry/loggregator-release/blob/82e93bab660bde17d9bf175e5927b06f4e58d65c/jobs/loggregator_trafficcontroller/spec#L70

Regards,

Benjamin

**Comment by toddboom** [comment]
@benjaminguttmann-avtq Thanks for opening an issue! I think you might be referring to `addrs`, which is just the pluralization of `addr`, an abbreviation for address. You can see it used throughout this repo - here's an example:
https://github.com/cloudfoundry/loggregator-release/blob/ac44ccc81f8b41b064a6ea452628cdf46c150872/jobs/reverse_log_proxy/templates/environment.sh.erb#L8

So, I think the line appears as intended. If I misunderstood your intent, feel free to comment on this issue again and we can reopen it.
