### ISSUE TITLE
"fixtures" and "_fixtures" directories

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/loggregator-release#375]
Hi,
my team would like to use loggregator-release-v102.0 and to approve that I've to analyze it's source code and the code of its dependencies chain, to be sure that they don't have problematic licenses.

Now some code and dependencies comes from directories "fixtures" and "_fixtures". 

Could you please tell me if what is valid for the buildpacks and specified at:
https://github.com/cloudfoundry/binary-buildpack/issues/21
is also applicable to loggregator-release-v102.0?

Thank for your help.

**Comment by bradylove** [comment]
@luisapace `loggregator-release` does not have any dependencies in `fixtures` or `_fixtures`. All the dependencies are git submodules under `src/`.

When a release is cut, all the dependencies listed in the package specs are included. (e.g. The dependencies for doppler can be found at [`packages/doppler/spec`](https://github.com/cloudfoundry/loggregator-release/blob/develop/packages/doppler/spec)) 

The same is true for https://github.com/cloudfoundry/statsd-injector-release/issues/7.
