### ISSUE TITLE
rlp process consumes all memory and swap when binding 5000 syslog drains

### ISSUE THREAD

**Issue by jomora** [cloudfoundry/loggregator-release#377]
## Steps to reproduce:

* cf-deployment version [`2.6.0`](https://github.com/cloudfoundry/cf-deployment/tree/v2.6.0) with loggregator `102.2`
* CF deployment with enough diego-cells and org quota to push 5000 apps and create 5000 services (we used 22 diego-cells, 50 dopplers, 20 log-apis, 20 adapters)
* Deploy any hello world app (it *doesn't even have to produce any logs*) 5000 times, e.g.
```bash
# -P runs 50 parallel pushs
seq 5000 | xargs -P 50 -I % cf push <app_name>_% > /dev/null
```
* You need a syslog drain endpoint reachable from adapter vms e.g. on <SYSLOG_DRAIN_IP>:4434. We were using an ELK stack with multiple syslog drain endpoints, but in the context of this issue we faked a syslog endpoint which discards all data using e.g.

```bash
# sudo apt-get install nmap (ncat is part of nmap)
# accept up to 5010 connections, listening on port 4434
ncat -4 -k --listen -p 4434 -m 5010 > /dev/null
```

to prove the point that the issue is not with the syslog drain endpoint.
* create user-provided services as per [docs](https://docs.cloudfoundry.org/devguide/services/log-management.html#step2):
```bash
seq 5000 | xargs -P 200 -I % cf create-user-provided-service test_syslog_% -l syslog://<SYSLOG_DRAIN_IP>:4434
```

* Create a 1-to-1 binding of service instances to apps, e.g. bin service_1 to app_1, service_2 to app_2, ...
```bash
seq 5000 |  xargs -P 200 -I % cf bind-service <app_name>_% test_syslog_%
```
## Observed behaviour

The `rlp` process on the `log-api` vms  consumes all memory and swap. Over time, some of the `log-api` vms fail and do not recover, i.e. swap and memory do not decrease even if you unbind the services.

See grafana screenshots in attached PDF
[rlp-overload_final.pdf](https://github.com/cloudfoundry/loggregator-release/files/2235757/rlp-overload_final.pdf)

We took PPROF dumps of rlp, see 
[dumps.tar.gz](https://github.com/cloudfoundry/loggregator-release/files/2235786/dumps.tar.gz)

Also see related discussion on slack:
* [https://cloudfoundry.slack.com/archives/C02HCCXV5/p1530637043000510](https://cloudfoundry.slack.com/archives/C02HCCXV5/p1530637043000510)
* [https://cloudfoundry.slack.com/archives/C02HCCXV5/p1530898439000106](https://cloudfoundry.slack.com/archives/C02HCCXV5/p1530898439000106)
* [https://cloudfoundry.slack.com/archives/C02HCCXV5/p1530898692000255](https://cloudfoundry.slack.com/archives/C02HCCXV5/p1530898692000255)

According to this the scaling should be fine to take the load of 5000 apps/bindings.

## Expected behaviour
rlp should not eat up all memory when binding the syslog drain services.

**Comment by bradylove** [comment]
@jomora thank you for the very detailed report. At first glance of the pprof dumps it appears there may be a go-routine leak. I am going to use your scaling and drain count to spin up an environment to attempt to reproduce.

**Comment by bradylove** [comment]
@jomora so far in our testing we have tested a scaled down version with 5 doppler's, 2 log-api's and 2 adapters with 500 drains. With this test we hit the RLP's max egress streams which caused a significant amount of logging on log-api and adapter VMs. 

Would you happen to have logs available for us to look at for doppler, log-api, and adapter to see if could possibly be a similar issue where our balancing load from adapter's to RLP's is not sufficient?

We are in the process of scaling up our deployment for further testing.

**Comment by bradylove** [comment]
@jomora sorry for the delay in communication. 

We have been doing a lot of testing around this and found another issue. When we increased the RLP's max egress streams to 1000 and applied some changes to the RLP and Doppler the CPU usage would improve greatly. However when we reverted the RLP's max egress streams back to 500 we would see the CPU for RLP and Doppler increase back to full CPU usage. We found that this was because when the RLP reaches the max egress streams it sends the gRPC error code for `ResourceExhausted`. However the syslog adapter was not properly handling this error and instead of just trying another gRPC connection, it would invalidate the connection the error was received on. This would cause all streams on that client connection to close.

We have fixes on the master branch of cloudfoundry/loggregator and are going to do some further validation.

**Comment by bradylove** [comment]
We have delivered some fixes to the develop branches of loggregator-release and cf-syslog-drain-release. Those fixes will be available next time we cut releases.

**Comment by ahevenor** [comment]
@jomora any luck with this fix? I am going to accept our tracker story. Please re-open if it doesn't work for you.

**Comment by jsievers** [comment]
@jomora is currently out of office but we will definitely do a test run using a bosh dev release of loggregator to see if your fixes help. it may take some time as the setup requires some effort but we'll report back here

**Comment by ahevenor** [comment]
@jsievers my bad. I'll schedule this for release ASAP (re-opening too).

**Comment by paolostivanin** [comment]
Hi, we tried your fixes (loggregator-dev, cf-syslog-drain-dev and loggregator-agent-dev) and they worked :)
We successfully deployed 5k apps with 5k bindings and each app was sending 20logs/seconds. The system (properly scaled) could handle the load without issues.

What we noticed is that when the system couldn't handle the load, 6 out of 20 adapter became unresponsive (= completely dead) and bosh resurrector kicked in (deleted the vm and recreated it)

**Comment by MasslessParticle** [comment]
When the adapters aren't properly scaled, we've noticed that I/O gets saturated and prevents the bosh director from contacting the vm. That's what prevents you from sshing to the machine and causes the BOSH resurrector to kick.
