### ISSUE TITLE
RLP Gateway CF Auth Proxy does not have default port in BOSH spec

### ISSUE THREAD

**Issue by bradylove** [cloudfoundry/loggregator-release#381]
The code for the RLP Gateway CF Auth Proxy has a default port of 8083, however the BOSH job spec does not have a default which means it must be provided.

https://github.com/cloudfoundry/loggregator-release/blob/develop/jobs/reverse_log_proxy_gateway_cf_auth_proxy/spec#L31-L32

We should add a default to the BOSH job spec to match what we have as the default in the code.

**Comment by apoydence** [comment]
We have merged the `reverse_log_proxy_gateway` with the `reverse_log_proxy_gateway_cf_auth_proxy` and therefore have deleted this job.
