### ISSUE TITLE
RLP Should expose certs via bosh link

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/loggregator-release#382]
The RLP certs should be discoverable: expose them via a bosh link

**Comment by bradylove** [comment]
I disagree with this. With BOSH 2 it is easy enough to create a cert signed by the loggregator CA. Certs/keys should be unique to a service. e.g. why would google and yahoo use the same cert?

**Comment by apoydence** [comment]
While I agree, CF and BOSH don't really seem to support any form of RBAC. Based on previous decisions within CF, I think we should move forward with exposing the link. We should lean on BOSH to allow for better control for the operator on which services can consume which links.

**Comment by apoydence** [comment]
Instead of exposing a link for each component (in this case the RLP), consumers should just use the link that doppler provides (https://github.com/cloudfoundry/loggregator-release/blob/4e84261c22294570da734950ebd7c667274f46fa/jobs/doppler/spec#L20-L25). This way consumers don't need intimate knowledge of the loggregator architecture.

**Comment by mattysweeps** [comment]
@poy wouldn't that require doppler to mark its `loggregator` link with `shared: true` in the PCF manifest?

I'm not sure how to use that link in a tile.yml configuration.

**Comment by mattysweeps** [comment]
@bradylove I found documentation on how to generate signed certificates in a tile form,

But is that possible directly with just a BOSH manifest? If so how do I do that? Do you have any documentation I can follow?

**Comment by bradylove** [comment]
@mattysweeps You can use BOSH variables to generate certificates. [Here](https://bosh.io/docs/variable-types/#certificate) is the BOSH documentation on how to do so, and [here](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L1936-L1943) is an example of how we are generating the certificate for the RLP in CF Deployment.
