### ISSUE TITLE
permission failure on loggregator_trafficcontroller_security due missing bpm config

### ISSUE THREAD

**Issue by renelehmann** [cloudfoundry/loggregator-release#385]
Hi 

Since loggregator release v104.0 and the use of **BPM** the loggregator_trafficcontroller cannot startup anymore due access violation on the security event log.
There are wrong file permission settings now.

Error:
```
2018/10/22 20:58:38.656639 Unable to open access log: open /var/vcap/sys/log/loggregator_trafficcontroller/loggregator_trafficcontroller_security_events.log: permission denied
panic: Unable to open access log: open /var/vcap/sys/log/loggregator_trafficcontroller/loggregator_trafficcontroller_security_events.log: permission denied
```

file permission:
``` 
log-api/0caa00a6-80c0-426a-9ea1-af7d19a0647e:~# ls -al /var/vcap/sys/log/loggregator_trafficcontroller/loggregator_trafficcontroller_security_events.log
---------- 1 vcap vcap 23711400 Oct 22 20:31 /var/vcap/sys/log/loggregator_trafficcontroller/loggregator_trafficcontroller_security_events.log
``` 

Related sources:
https://github.com/cloudfoundry/loggregator/blob/d4c6cfea2e83497ed922a08ad7ebedba947e82b3/trafficcontroller/app/traffic_controller.go#L172-L176

BPM commit:
https://github.com/cloudfoundry/loggregator-release/commit/f72613de0cefaf11808c900efd7d922eefd57ae5

Thanks for looking into it and fixing ;-)
Rene

**Comment by jtuchscherer** [comment]
@renelehmann Thanks for troubleshooting this. We will take a look and fix it ASAP.

**Comment by poy** [comment]
@renelehmann Good catch! Fixed: https://github.com/cloudfoundry/loggregator/commit/5555777b5ebcfa90a3b8bb3e9d1fcfdd6f8ab2c4

**Comment by jtuchscherer** [comment]
This has been done and fixed. Thanks for reporting this.
