### ISSUE TITLE
App logs are not showed when running `cf logs $APP --recent` if the message is larger than GRPC maximum message size

### ISSUE THREAD

**Issue by XuejiaoZhang** [cloudfoundry/loggregator-release#387]
- [*] I found a bug - here are some steps to reproduce it.

Loggregator version: 103.0 (also, v101.4)
Loggregator-agent version: 2.0

Here is how to reproduce it.
```
mkdir -p /tmp/testlog &&  cd /tmp/testlog && touch .testlog && cf push -i 1 testlog-2 -u process -c 'data=$(seq -s " " 1 20000); while true; do echo "$data"; done' -b https://github.com/cloudfoundry/binary-buildpack
```
App logs are not showed when running cf logs $APP --recent, but could be got from syslog-drain and from running cf logs $APP.
```
$ cf logs testlog-2  --recent
Retrieving logs for app testlog-2 in org $org / space $space as $someone ...
```
Here are related logs:
`Error: Received message larger than max (6374240 vs. 4194304)`

When the "recent logs" exceeds the GRPC maximum message size 4M, we expect a friendly way to handle it.

**Comment by MasslessParticle** [comment]
Hi @XuejiaoZhang, we have restructured how recent logs and metrics come from the loggregator-trafficcontroller as of version 103.2. That may solve your issue

**Comment by jtuchscherer** [comment]
@XuejiaoZhang this should be fixed in the current develop version. Would you mind giving this a try?

Please re-open this issue if you still run into problems.
