### ISSUE TITLE
doppler.outgoing_port is unused

### ISSUE THREAD

**Issue by poy** [cloudfoundry/loggregator-release#390]
It looks like `doppler.outgoing_port` is redundant to `loggregator.outgoing_dropsonde_port`. It also looks like `loggregator.outgoing_dropsonde_port` is exported via bosh links. Doing a quick search, it looks like the only other place `doppler.outgoing_port` is used is some [docs](https://github.com/cloudfoundry/loggregator-release/blob/a13ca4d9f75cc05a2e4209f78534e5260f4401b2/docs/cert-config.md#L166) (which need updating).

https://github.com/cloudfoundry/loggregator-release/blob/f9ceccb3523e67321e1e700716d1dab11e7de9c3/jobs/loggregator_trafficcontroller/spec#L60-L62

https://github.com/cloudfoundry/loggregator-release/blob/f9ceccb3523e67321e1e700716d1dab11e7de9c3/jobs/loggregator_trafficcontroller/spec#L41-L43

**Comment by jtuchscherer** [comment]
Thanks for reporting this @poy 
Glad you are still poking around in these repos.

This issue should be fixed in this commit: 8d9ee18459d971c7e771a3b77d42f6e2614b64fc
