### ISSUE TITLE
update loggregator-release to include prometheus 2.12.0

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/loggregator-release#394]
Hi, my team would use loggregator-release (V104.4 or higher) and to approve that I've to verify that all its licenses are acceptable.

During my analysis I've found a problematic license in the code of package prometheus 2.10.0 (dependency of loggregator-release, and so I've opened an issue on it: prometheus/prometheus#5783

(please note that I've opened the issue on 2.9.2 but 2.10.0 have the same problem).

Its developers have solved the issue in prometheus 2.12.0 (see details in the above issue).

So, I kindly ask you to update loggregator-release to use the new version of prometheus.

Thanks a lot.

**Comment by luisapace** [comment]
Hi, do you have any new on this issue? Thanks

**Comment by luisapace** [comment]
@kitemongerer Hi Max, my colleague Michele has sent you an email with details, please let me know if you have not received.

Thanks

**Comment by kitemongerer** [comment]
@luisapace I did not receive the email. It would be great if it would be posted in the #loggregator channel in https://cloudfoundry.slack.com/messages/C02HCCXV5 so the rest of the team can assist

**Comment by mlicursi** [comment]
The dependency chain that links to prometheus is the following

https://github.com/cloudfoundry/loggregator-release/tree/v104.4/src/code.cloudfoundry.org shows this link: https://github.com/cloudfoundry/log-cache/tree/b58cf4e7bc872866d692b7757683ce6711bc182f. 
inside log-cache you can then find  log-cache/internal/promql/promql.go  . 
The promql.go has : "github.com/prometheus/prometheus/pkg/labels"

"github.com/prometheus/prometheus/promql"


"github.com/prometheus/prometheus/storage" 
among its imports

This is surprising as the link says: "bump log-cache to version that doesn't require prometheus "

Hope this clarifies the issue raised by Luisa

**Comment by luisapace** [comment]
@kitemongerer Hi, are there any updates? Thanks

**Comment by kitemongerer** [comment]
@luisapace It looks like the current version of loggregator-release has this log-cache commit in its go.mod: https://github.com/cloudfoundry/log-cache-release/commit/8c97ac62a57b3aafd23368b7e50d73d2f56e5770#diff-12842eeae4e409eb286af05c15acac3e

which has Prometheus 2.12.0... is that what you're looking for?

**Comment by luisapace** [comment]
@kitemongerer yes, thanks. May I ask you if you can confirm what is the current version? 103.4.3?

**Comment by kitemongerer** [comment]
It's 106.2.0

**Comment by luisapace** [comment]
just released! thanks a lot again for your help

**Comment by luisapace** [comment]
@kitemongerer thanks a lot
