### ISSUE TITLE
RLP won't shut down sometimes

### ISSUE THREAD

**Issue by Benjamintf1** [cloudfoundry/loggregator-release#404]
Thanks for your submission!

Here are some guidance for submitting your issue.

Tell us why you are submitting?

- [x] I found a bug - here are some steps to recreate it.
- [ ] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

IDK, deploy a bunch of times.

**Comment by pianohacker** [comment]
This is fixed in 106.2.8 and 106.3.10.
