### ISSUE TITLE
Bionic stemcell: "killall" behaves differently

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/loggregator-release#411]
- [X] I found a bug - here are some steps to recreate it.
- [ ] I have an idea for a new feature - please document as "As a user, I would
like to..."
- [ ] I am having trouble getting setup, understanding documentation, or using
Loggregator in some way - please highlight any resources you are using.
- [ ] This is an architecture change that will result in cleaner more efficient
code - Tell us why you think this is a good idea.

Hi Loggregator Team,

we are evaluating Cloud Foundry on the Bionic stemcell. Almost everything runs fine, but the BOSH jobs that use a "killall" command in the drain script cause problems. On Ubuntu Xenial, the command "killall rlp" worked. On Bionic, we get:
```
# killall rlp
rlp: no process found
# echo $?
1
```
This leads to orphaned processes and failing restarts. These two jobs from the loggregator release are affected:
https://github.com/cloudfoundry/loggregator-release/tree/develop/jobs/loggregator_trafficcontroller
https://github.com/cloudfoundry/loggregator-release/tree/develop/jobs/reverse_log_proxy

Stemcell details:
bosh-aws-xen-hvm-ubuntu-xenial-go_agent  621.95  ubuntu-xenial (uses killall (PSmisc) 22.21)
bosh-aws-xen-hvm-ubuntu-bionic-go_agent  0.6     ubuntu-bionic (uses killall (PSmisc) 23.1)

We are not sure however how to modify the "killall" command so that it works on Xenial as well as Bionic.

Thanks for you support and Best Regards,

  Jochen.

**Comment by jochenehret** [comment]
Issue is probably caused by https://gitlab.com/psmisc/psmisc/-/issues/23
We try to evaluate a later version of killall/psmisc.

**Comment by jochenehret** [comment]
I'm closing this issue as it is not a problem with this BOSH release. We just need an updated stemcell with a fixed version of "killall". Sorry for any confusion caused.

**Comment by StefanWutz** [comment]
Related to https://bugs.launchpad.net/ubuntu/+source/psmisc/+bug/1790732.

**Comment by jochenehret** [comment]
Re-opening this issue. It's currently unclear if we get a Bionic stemcell with a fixed "killall" version.

Loggregator team: Can you find an alternative implementation that works on Xenial as well as on Bionic?

**Comment by jochenehret** [comment]
Proposed fix: https://github.com/cloudfoundry/loggregator-release/pull/412
We've tested the fixed loggregator-release on the Xenial 621.97 and Bionic 0.6 stemcells (migrated from Xenial to Bionic and back).

**Comment by Benjamintf1** [comment]
I think this is done.
